---
# Arcbase non usa initramfs: root su ext4 o xfs, senza cifratura né LVM.
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 512MiB
    minimumSize: 300MiB
    label: "EFI"
efiSystemPartition: "/boot/efi"
userSwapChoices: [ none, file ]
initialSwapChoice: none
drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: erase
defaultPartitionTableType: gpt
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4", "xfs" ]
enableLuksAutomatedPartitioning: false
