---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - wheel
    - audio
    - video
    - input
    - render
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: true
doReusePassword: true
passwordRequirements:
    nonempty: true
    minLength: 4
allowWeakPasswords: true
allowWeakPasswordsDefault: false
user:
    shell: /bin/bash
    forbidden_names: [ root, live ]
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "arcbase-${cpu}"
