---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
showDonateUrl: false
requirements:
    requiredStorage: 25
    requiredRam: 2.0
    internetCheckUrl: https://geo.mirror.pkgbuild.com
    check: [ storage, ram, power, internet, root, screen ]
    required: [ storage, ram, root ]
