# Arcbase Desktop — configurazione di Calamares
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id:       pre
  module:   shellprocess
  config:   shellprocess-pre.conf
- id:       post
  module:   shellprocess
  config:   shellprocess-post.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - shellprocess@pre
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - shellprocess@post
  - umount
- show:
  - finished

branding: arcbase
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
